var OAO=OAO||{};OAO.q=OAO.q||{};OAO.q.c=OAO.q.c||[];
(function(){OAO.q.ias=OAO.q.ias||[];OAO.q.ias.push(["addVisitorData","usePOST",!0]);var l=window.location.hostname||"",m,w,x;m=l.indexOf(".ionos.");w=l.indexOf(".server.lan");x=l.indexOf(".localhost");if(-1===m&&-1===w&&-1===x)return!1;m=l.substr(m+7);if(0===m.indexOf("de"))OAO.q.c.push(["setDefaultMarket","DE"]),OAO.q.c.push(["setDefaultLanguage","de_DE"]),OAO.q.c.push(["setDefaultTenant","IONOS_DE"]);else if(0===m.indexOf("ca"))OAO.q.c.push(["setDefaultMarket","CA"]),OAO.q.c.push(["setDefaultLanguage",
"en_CA"]),OAO.q.c.push(["setDefaultTenant","IONOS_CA"]);else if(0===m.indexOf("es"))OAO.q.c.push(["setDefaultMarket","ES"]),OAO.q.c.push(["setDefaultLanguage","es_ES"]),OAO.q.c.push(["setDefaultTenant","IONOS_ES"]);else if(0===m.indexOf("fr"))OAO.q.c.push(["setDefaultMarket","FR"]),OAO.q.c.push(["setDefaultLanguage","fr_FR"]),OAO.q.c.push(["setDefaultTenant","IONOS_FR"]);else if(0===m.indexOf("it"))OAO.q.c.push(["setDefaultMarket","IT"]),OAO.q.c.push(["setDefaultLanguage","it_IT"]),OAO.q.c.push(["setDefaultTenant",
"IONOS_IT"]);else if(0===m.indexOf("mx"))OAO.q.c.push(["setDefaultMarket","MX"]),OAO.q.c.push(["setDefaultLanguage","es_MX"]),OAO.q.c.push(["setDefaultTenant","IONOS_MX"]);else if(0===m.indexOf("pl"))OAO.q.c.push(["setDefaultMarket","PL"]),OAO.q.c.push(["setDefaultLanguage","pl_PL"]),OAO.q.c.push(["setDefaultTenant","IONOS_PL"]);else if(0===m.indexOf("co.uk")||0===m.indexOf("uk"))OAO.q.c.push(["setDefaultMarket","UK"]),OAO.q.c.push(["setDefaultLanguage","en_GB"]),OAO.q.c.push(["setDefaultTenant",
"IONOS_UK"]);else if(0===m.indexOf("com"))OAO.q.c.push(["setDefaultMarket","US"]),OAO.q.c.push(["setDefaultLanguage","en_US"]),OAO.q.c.push(["setDefaultTenant","IONOS_US"]);else if(-1!==l.indexOf("de.")||-1!==l.indexOf("de-"))OAO.q.c.push(["setDefaultMarket","DE"]),OAO.q.c.push(["setDefaultLanguage","de_DE"]),OAO.q.c.push(["setDefaultTenant","IONOS_DE"]);else if(-1!==l.indexOf("ca.")||-1!==l.indexOf("ca-"))OAO.q.c.push(["setDefaultMarket","CA"]),OAO.q.c.push(["setDefaultLanguage","en_CA"]),OAO.q.c.push(["setDefaultTenant",
"IONOS_CA"]);else if(-1!==l.indexOf("es.")||-1!==l.indexOf("es-"))OAO.q.c.push(["setDefaultMarket","ES"]),OAO.q.c.push(["setDefaultLanguage","es_ES"]),OAO.q.c.push(["setDefaultTenant","IONOS_ES"]);else if(-1!==l.indexOf("fr.")||-1!==l.indexOf("fr-"))OAO.q.c.push(["setDefaultMarket","FR"]),OAO.q.c.push(["setDefaultLanguage","fr_FR"]),OAO.q.c.push(["setDefaultTenant","IONOS_FR"]);else if(-1!==l.indexOf("it.")||-1!==l.indexOf("it-"))OAO.q.c.push(["setDefaultMarket","IT"]),OAO.q.c.push(["setDefaultLanguage",
"it_IT"]),OAO.q.c.push(["setDefaultTenant","IONOS_IT"]);else if(-1!==l.indexOf("mx.")||-1!==l.indexOf("mx-"))OAO.q.c.push(["setDefaultMarket","MX"]),OAO.q.c.push(["setDefaultLanguage","es_MX"]),OAO.q.c.push(["setDefaultTenant","IONOS_MX"]);else if(-1!==l.indexOf("pl.")||-1!==l.indexOf("pl-"))OAO.q.c.push(["setDefaultMarket","PL"]),OAO.q.c.push(["setDefaultLanguage","pl_PL"]),OAO.q.c.push(["setDefaultTenant","IONOS_PL"]);else if(-1!==l.indexOf("uk.")||-1!==l.indexOf("gb.")||-1!==l.indexOf("uk-")||
-1!==l.indexOf("gb-"))OAO.q.c.push(["setDefaultMarket","UK"]),OAO.q.c.push(["setDefaultLanguage","en_GB"]),OAO.q.c.push(["setDefaultTenant","IONOS_UK"]);else if(-1!==l.indexOf("us.")||-1!==l.indexOf("com.")||-1!==l.indexOf("us-")||-1!==l.indexOf("com-"))OAO.q.c.push(["setDefaultMarket","US"]),OAO.q.c.push(["setDefaultLanguage","en_US"]),OAO.q.c.push(["setDefaultTenant","IONOS_US"])})();
(function(){if(window.OAO&&window.OAO.mobile){var l=document.querySelectorAll(".pagemessage[level\x3dinfo], .pagemessage[level\x3dsuccess], .custom-success-message .main-message, .pagemessages-container .subheadline-section, .sheet__section.sheet__section--activating .headline, .sheet__section.sheet__section--success .headline, .sheet__section.sheet__section--warning .headline"),m=document.querySelector(".abort-transaction")||!1;!1!==m&&m.addEventListener?m.addEventListener("click",function(){window.OAO.mobile.abortedAction()}):
!1!==m&&m.attachEvent&&m.attachEvent("onclick",function(){window.OAO.mobile.abortedAction()});l&&0<l.length&&(l=l[0],window.OAO.mobile.finishedAction(l.textContent||l.innerText))}})();(function(){OAO.q.privacyconsent=OAO.q.privacyconsent||[];OAO.q.privacyconsent.push(["addMarketingCallback",function(){OAO.q.t=OAO.q.t||[];OAO.q.t.push(["setUserConsent",!0])}])})();OAO.q.pageintegration=OAO.q.pageintegration||[];OAO.q.notifications=OAO.q.notifications||[];OAO.q.navigation=OAO.q.navigation||[];
OAO.q.navigation.push(["setAppSwitchDisabled",!0]);OAO.q.navigation.push(["hideOffersIcon","always"]);(function(){OAO.q.pageintegration.push(["disableDeeplinkingOnInit"]);OAO.q.pageintegration.push(["setForceShownIFrame"])})();
(function(){OAO.q.notifications.push(["isPushSupported",function(l){if(l&&(l=window.location.hostname||!1,!1!==l)){l=l.replace("login.",".");var m=new Date;m.setTime(m.getTime()+864E5);m="expires\x3d"+m.toUTCString();document.cookie="supportsBrowserPush\x3dtrue;"+m+";domain\x3d"+l+";path\x3d/"}}])})();OAO.q.c.push(["setApplication","CENTRAL_LOGIN"]);OAO.q.c.push(["loadModule","adserver"]);OAO.q.c.push(["loadModule","surveys"]);OAO.q.c.push(["loadModule","statuspage"]);OAO.q.c.push(["loadModule","pushnotifications"]);
OAO.q.c.push(["loadModule","privacy-consent"]);(function(){-1!==(window.location.hostname||"").indexOf(".cpwaterloo")?(OAO.q.navigation.push(["setMode","STAGE"]),OAO.q.c.push(["loadModule","inpagelayer-prelive"]),OAO.q.c.push(["loadModule","globalnavigation-prelive"])):(OAO.q.c.push(["loadModule","inpagelayer"]),OAO.q.c.push(["loadModule","globalnavigation"]))})();
(function(){function l(g){var h=w[g];if(void 0!==h)return h.exports;h=w[g]={exports:{}};return m[g](h,h.exports,l),h.exports}var m={610:function(g,h,c){var f=c(756),d=c(887),b=c(664),e=c(242);g.exports={init:function(){},setApplication:function(a){f.setApplication(a)},setPageName:function(a){f.setPageName(a)},setFrontendToken:function(a){d.setFrontendToken(a)},setContractHash:function(a){d.setContractHash(a)},setContract:function(a){d.setContract(a)},setBasketBaseUri:function(a){b.setBasketBaseUri(a)},
setShopApiBaseUri:function(a){b.setShopApiBaseUri(a)},setMode:function(a){b.setMode(a)},setHost:function(a){b.setHost(a)},setMarket:function(a){b.setMarket(a)},setDefaultMarket:function(a){b.setDefaultMarket(a)},setLanguage:function(a){b.setLanguage(a)},setDefaultLanguage:function(a){!1===b.getLanguage()&&b.setLanguage(a)},setTenant:function(a){b.setTenant(a)},setDefaultTenant:function(a){b.setDefaultTenant(a)},loadModule:function(a){try{c(767)("./"+a)}catch(n){e.reportError(n)}},data:{get visitor(){var a=
{};return d.getFrontendToken()&&(a.frontendToken=d.getFrontendToken()),d.getContractHash()&&(a.contractHash=d.getContractHash()),a},get tracking(){var a={};return f.getApplication()&&(a.application=f.getApplication()),f.getPageName()&&(a.page=f.getPageName()),a},get settings(){var a={};return a.isProd=b.isProd(),a.market=b.getMarket(),a.language=b.getLanguage(),a.host=b.getHost(),a.shopApiBaseUri=b.getShopApiBaseUri(),a.basketBaseUri=b.getBasketBaseUri(),a.tenant=b.getTenant(),a}},__version:b.getVersion()}},
39:function(g,h,c){function f(){var a=c(885);e.getFrontendToken()&&a.OAO.q.ias.push(["setFrontendSessionToken",e.getFrontendToken()]);e.getContractHash()&&a.OAO.q.ias.push(["setHashContractId",e.getContractHash()]);e.getContract()&&a.OAO.q.ias.push(["addVisitorData","contract",e.getContract()])}function d(){p.OAO.q.ias.push(["setMarket",a.getMarket()]);p.OAO.q.ias.push(["setLanguage",a.getLanguage()]);p.OAO.q.ias.push(["setTenant",a.getTenant()]);a.getShopApiBaseUri()&&p.OAO.q.ias.push(["addVisitorData",
"shopApiBaseUri",a.getShopApiBaseUri()]);a.getBasketBaseUri()&&p.OAO.q.ias.push(["addVisitorData","basketBaseUri",a.getBasketBaseUri()])}function b(){p.OAO.q.ias.push(["setApplication",n.getApplication()]);p.OAO.q.ias.push(["setPage",n.getPageName()])}var e=c(887),a=c(664),n=c(756),k=c(85);g=c(616);var p=c(885);p.OAO=p.OAO||{};p.OAO.q=p.OAO.q||{};p.OAO.q.ias=p.OAO.q.ias||[];p.OAO.q.ias.push(["setHost",!1]);e.addChangeListener(f);a.addChangeListener(d);n.addChangeListener(b);f();d();b();g.onQueueFinished(function(){k.loadModule("ias/js/ias",
"5.61.2")})},11:function(g,h,c){function f(){k.OAO.q.navigation.push(["setFrontendToken",e.getFrontendToken()]);e.getContract()&&k.OAO.q.navigation.push(["setContract",e.getContract()])}function d(){k.OAO.q.navigation.push(["setMarket",a.getMarket()]);k.OAO.q.navigation.push(["setLanguage",a.getLanguage()]);k.OAO.q.navigation.push(["setTenant",a.getTenant()]);k.OAO.q.navigation.push(["setBasePath",a.getHost()+"/navi-prelive/"])}function b(){k.OAO.q.navigation.push(["setClient",n.getApplication()]);
k.OAO.q.navigation.push(["setPageName",n.getPageName()])}var e=c(887),a=c(664),n=c(756);g=c(85);var k=c(885);k.OAO=k.OAO||{};k.OAO.q=k.OAO.q||{};k.OAO.q.navigation=k.OAO.q.navigation||[];f();d();b();e.addChangeListener(f);a.addChangeListener(d);n.addChangeListener(b);g.loadModule("navi-prelive/js/navigation","5.46.0")},609:function(g,h,c){function f(){k.OAO.q.navigation.push(["setFrontendToken",e.getFrontendToken()]);e.getContract()&&k.OAO.q.navigation.push(["setContract",
e.getContract()])}function d(){k.OAO.q.navigation.push(["setMarket",a.getMarket()]);k.OAO.q.navigation.push(["setLanguage",a.getLanguage()]);k.OAO.q.navigation.push(["setTenant",a.getTenant()]);k.OAO.q.navigation.push(["setBasePath",a.getHost()+"/navi/"]);a.getShopApiBaseUri()&&k.OAO.q.navigation.push(["setShopApiBaseUri",a.getShopApiBaseUri()])}function b(){k.OAO.q.navigation.push(["setClient",n.getApplication()]);k.OAO.q.navigation.push(["setPageName",n.getPageName()])}var e=c(887),a=c(664),n=c(756);
g=c(85);var k=c(885);k.OAO=k.OAO||{};k.OAO.q=k.OAO.q||{};k.OAO.q.navigation=k.OAO.q.navigation||[];f();d();b();e.addChangeListener(f);a.addChangeListener(d);n.addChangeListener(b);g.loadModule("navi/js/navigation","5.46.0")},177:function(g,h,c){function f(){a.OAO.q.pageintegration.push(["setMarket",b.getMarket()]);a.OAO.q.pageintegration.push(["setLanguage",b.getLanguage()]);a.OAO.q.pageintegration.push(["setBasePath",b.getHost()+"/inpagelayer-prelive/"])}function d(){a.OAO.q.pageintegration.push(["setClient",
e.getApplication()]);a.OAO.q.pageintegration.push(["setPageName",e.getPageName()])}var b=c(664),e=c(756);g=c(85);var a=c(885);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.pageintegration=a.OAO.q.pageintegration||[];f();d();b.addChangeListener(f);e.addChangeListener(d);g.loadModule("inpagelayer-prelive/js/inpagelayer","4.3.6")},362:function(g,h,c){function f(){a.OAO.q.pageintegration.push(["setMarket",b.getMarket()]);a.OAO.q.pageintegration.push(["setLanguage",b.getLanguage()]);
a.OAO.q.pageintegration.push(["setBasePath",b.getHost()+"/inpagelayer/"])}function d(){a.OAO.q.pageintegration.push(["setClient",e.getApplication()]);a.OAO.q.pageintegration.push(["setPageName",e.getPageName()])}var b=c(664),e=c(756);g=c(85);var a=c(885);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.pageintegration=a.OAO.q.pageintegration||[];f();d();b.addChangeListener(f);e.addChangeListener(d);g.loadModule("inpagelayer/js/inpagelayer","4.3.6")},319:function(g,h,c){function f(){a.OAO.q.passwordindicator.push(["setMarket",
b.getMarket()]);a.OAO.q.passwordindicator.push(["setLanguage",b.getLanguage()]);a.OAO.q.passwordindicator.push(["setBasePath",b.getHost()+"/password-indicator/"])}function d(){a.OAO.q.passwordindicator.push(["setClient",e.getApplication()]);a.OAO.q.passwordindicator.push(["setPageName",e.getPageName()])}var b=c(664),e=c(756);g=c(85);var a=c(885);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.passwordindicator=a.OAO.q.passwordindicator||[];f();d();b.addChangeListener(f);e.addChangeListener(d);g.loadModule("password-indicator/js/password-indicator",
"2.11.0")},8:function(g,h,c){function f(){b.OAO.q.privacyconsent.push(["setMarket",d.getMarket()]);b.OAO.q.privacyconsent.push(["setLanguage",d.getLanguage()])}g=c(85);var d=c(664),b=c(885);b.OAO=b.OAO||{};b.OAO.q=b.OAO.q||{};b.OAO.q.privacyconsent=b.OAO.q.privacyconsent||[];f();d.addChangeListener(f);g.loadModule("privacyconsent-prelive/js/privacyconsent","3.0.8")},731:function(g,h,c){function f(){b.OAO.q.privacyconsent.push(["setMarket",d.getMarket()]);
b.OAO.q.privacyconsent.push(["setLanguage",d.getLanguage()])}g=c(85);var d=c(664),b=c(885);b.OAO=b.OAO||{};b.OAO.q=b.OAO.q||{};b.OAO.q.privacyconsent=b.OAO.q.privacyconsent||[];f();d.addChangeListener(f);g.loadModule("privacyconsent/js/privacyconsent","3.0.8")},229:function(g,h,c){function f(){k.OAO.q.notifications.push(["setFrontendToken",e.getFrontendToken()])}function d(){k.OAO.q.notifications.push(["setMarket",a.getMarket()]);k.OAO.q.notifications.push(["setLanguage",a.getLanguage()]);
k.OAO.q.notifications.push(["setBasePath",a.getHost()+"/pushnotifications/"])}function b(){k.OAO.q.notifications.push(["setClient",n.getApplication()]);k.OAO.q.notifications.push(["setPageName",n.getPageName()])}var e=c(887),a=c(664),n=c(756);g=c(85);var k=c(885);k.OAO=k.OAO||{};k.OAO.q=k.OAO.q||{};k.OAO.q.notifications=k.OAO.q.notifications||[];f();d();b();e.addChangeListener(f);a.addChangeListener(d);n.addChangeListener(b);g.loadModule("pushnotifications/js/pushnotifications","2.3.9")},
119:function(g,h,c){function f(){a.OAO.q.statuspage.push(["setMarket",b.getMarket()]);a.OAO.q.statuspage.push(["setLanguage",b.getLanguage()]);a.OAO.q.statuspage.push(["setBasePath",b.getHost()+"/statuspage/"])}function d(){a.OAO.q.statuspage.push(["setClient",e.getApplication()]);a.OAO.q.statuspage.push(["setPageName",e.getPageName()])}var b=c(664),e=c(756);g=c(85);var a=c(885);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.statuspage=a.OAO.q.statuspage||[];f();d();b.addChangeListener(f);e.addChangeListener(d);
g.loadModule("statuspage/js/statuspage","2.1.4")},150:function(g,h,c){function f(){var a=c(885);e.getFrontendToken()&&a.OAO.q.surveys.push(["setFrontendSessionToken",e.getFrontendToken()]);e.getContract()&&a.OAO.q.surveys.push(["setContract",e.getContract()])}function d(){p.OAO.q.surveys.push(["setMarket",a.getMarket()]);p.OAO.q.surveys.push(["setLanguage",a.getLanguage()]);p.OAO.q.surveys.push(["setTenant",a.getTenant()])}function b(){p.OAO.q.surveys.push(["setClient",n.getApplication()]);
p.OAO.q.surveys.push(["setPage",n.getPageName()])}var e=c(887),a=c(664),n=c(756),k=c(85);g=c(616);var p=c(885);p.OAO=p.OAO||{};p.OAO.q=p.OAO.q||{};p.OAO.q.surveys=p.OAO.q.surveys||[];e.addChangeListener(f);a.addChangeListener(d);n.addChangeListener(b);f();d();b();g.onQueueFinished(function(){k.loadModule("surveys/js/surveys","1.6.0")})},456:function(g,h,c){function f(){k.OAO.q.t.push(["setFrontendToken",e.getFrontendToken()])}function d(){k.OAO.q.t.push(["setMarket",a.getMarket()]);
k.OAO.q.t.push(["setTenant",a.getTenant()])}function b(){k.OAO.q.t.push(["setApplication",n.getApplication()]);k.OAO.q.t.push(["setPage",n.getPageName()])}var e=c(887),a=c(664),n=c(756);g=c(85);var k=c(885);k.OAO=k.OAO||{};k.OAO.q=k.OAO.q||{};k.OAO.q.t=k.OAO.q.t||[];f();d();b();e.addChangeListener(f);a.addChangeListener(d);n.addChangeListener(b);g.loadModule("t/js/t","1.10.2")},488:function(g,h,c){function f(){a.OAO.q.tour.push(["setMarket",b.getMarket()]);a.OAO.q.tour.push(["setLanguage",
b.getLanguage()]);a.OAO.q.tour.push(["setBasePath",b.getHost()+"/welcometour/"])}function d(){a.OAO.q.tour.push(["setClient",e.getApplication()]);a.OAO.q.tour.push(["setPageName",e.getPageName()])}var b=c(664),e=c(756);g=c(85);var a=c(885);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.tour=a.OAO.q.tour||[];f();d();b.addChangeListener(f);e.addChangeListener(d);g.loadModule("welcometour/js/welcome-tour","3.0.0")},664:function(g,h,c){var f;h=c(584);var d=h.Mode,b=h.Market,e=h.Language,
a=h.Tenant;h=c(418);c=c(187).EventEmitter;var n=d.PROD,k=!1,p=b.DE,l=!1,m=a.IONOS_DE,t=!1,q=!1,r=!1;c=h({},c.prototype,{emitChange:function(){this.emit("change")},addChangeListener:function(a){this.on("change",a)},getVersion:function(){return"1.0.0"},isProd:function(){return n===d.PROD},setMode:function(a){a?(a=a.toUpperCase(),d[a]||(a=d.PROD)):a=d.PROD;var b=n!==a;n=a;b&&this.emitChange()},getMarket:function(){return k||p},setMarket:function(a){a?("GB"===(a=a.toUpperCase())&&(a=b.UK),b[a]||(a=b.DE)):
a=b.DE;var d=k!==a;k=a;d&&this.emitChange()},setDefaultMarket:function(a){a?("GB"===(a=a.toUpperCase())&&(a=b.UK),b[a]||(a=b.DE)):a=b.DE;var d=p!==a;p=a;d&&this.emitChange()},getLanguage:function(){return l},setLanguage:function(a){if(a&&-1!==a.indexOf("_")){var b,d,c=a.indexOf("_");(b=a.substr(0,c)||"",d=a.substr(c+1)||"",b=b.toLowerCase(),d=d.toUpperCase(),e[a=b+"_"+d])?(b=l!==a,l=a,b&&this.emitChange()):l=!1}else l=!1},getTenant:function(){return t||m},setTenant:function(b){b?(b=b.toUpperCase(),
a[b]||(b=a.IONOS_DE)):b=a.IONOS_DE;var d=t!==b;t=b;d&&this.emitChange()},setShopApiBaseUri:function(a){var b=q!==a;q=a||!1;b&&this.emitChange()},getShopApiBaseUri:function(){return q},setBasketBaseUri:function(a){var b=r!==a;r=a||!1;b&&this.emitChange()},getBasketBaseUri:function(){return r},setDefaultTenant:function(b){b?(b=b.toUpperCase(),a[b]||(b=a.IONOS_DE)):b=a.IONOS_DE;var d=m!==b;m=b;d&&this.emitChange()},getHost:function(){return f},setHost:function(a){var b=f!==a;f=a||!1;b&&this.emitChange()}});
g.exports=c},756:function(g,h,c){h=c(418);c=c(187).EventEmitter;var f=!1,d=!1;c=h({},c.prototype,{emitChange:function(){this.emit("change")},addChangeListener:function(b){this.on("change",b)},getApplication:function(){return f},setApplication:function(b){var d=f!==b;f=b||!1;d&&this.emitChange()},getPageName:function(){return d},setPageName:function(b){if(b){try{b=(b=(b=(b=b.replaceAll(/^\s+|\s+$/g,"")).replaceAll(/\s\s+/g," ")).replaceAll(" ","-")).replaceAll(/#(.*)/g,"")}catch(a){b=(b=(b=(b=b.replace(/^\s+|\s+$/g,
"")).replace(/\s\s+/g," ")).replace(" ","-")).replace(/#(.*)/g,"")}b=b.replace(/;jsessionid=([A-Za-z0-9.]+)/,"")}var c=d!==b;d=b||!1;c&&this.emitChange()}});g.exports=c},887:function(g,h,c){h=c(418);c=c(187).EventEmitter;var f=!1,d=!1,b=!1;c=h({},c.prototype,{emitChange:function(){this.emit("change")},addChangeListener:function(b){this.on("change",b)},getFrontendToken:function(){return f},setFrontendToken:function(b){var a=f!==b;f=b||!1;a&&this.emitChange()},getContractHash:function(){return d},getContract:function(){return b},
setContractHash:function(b){var a=d!==b;d=b||!1;a&&this.emitChange()},setContract:function(d){var a=b!==d;b=d||!1;a&&this.emitChange()}});g.exports=c},355:function(g,h,c){var f=c(929);h=c(664);c=c(756);(f=f.getDefaultHostnameByScriptTag())&&h.setHost(f);(h=function(){var d=window.location;if(!d||!d.pathname)return!1;for(var d=d.pathname.split("/"),b=0;b<d.length;b+=1)if(d[b]&&""!==d[b]){var c=d[b].split("#",2)[0].split("\\?",2)[0].split(";",2)[0];if(c&&""!==c)return c}return"HOME"}())&&c.setPageName(h);
g.exports={}},616:function(g,h,c){h=c(187).EventEmitter;var f=c(418);c=c(885);c.OAO=c.OAO||{};c.OAO.q=c.OAO.q||{};var d=c.OAO.q.c||[],b=!1,e=f({},h.prototype,{addPushListener:function(a){this.on("push",a)},removePushListener:function(a){this.removeListener("push",a)},onQueueFinished:function(a){b?window.setTimeout(a,0):this.on("ready",a)},push:function(){if(!(1>arguments.length)){var a=0>=arguments.length?void 0:arguments[0];if(a&&a.length&&!(1>a.length)){var b=a[0],a=a.slice(1);this.emit("push",
b,a)}}},process:function(){for(var a=0;a<d.length;a+=1){var c=[];c.push(d[a]);e.push.apply(e,c)}d=[];b=!0;this.emit("ready")}});c.OAO.q.c={push:function(){for(var a=arguments.length,b=Array(a),d=0;d<a;d++)b[d]=arguments[d];e.push.apply(e,b)}};g.exports=e},85:function(g,h,c){var f=c(664),d=c(929),b=c(318);g.exports={loadScript:d.loadScript,loadModule:function(c,a,h){c={host:f.getHost(),path:c+".js",query:{v:a||1}};f.isProd()&&(c.protocol="https");d.loadScript(b.build(c),h)}}},925:function(g,h,c){var f=
c(616),d=c(610),b=c(242);b.setClient("TAG_MANAGER");b.setClientVersion("1.0.0");b.setSentryDsn("https://236c7da13ef44014830813657f2e5fb7@sentry.ionos.com/25");b.setSentryProject("tagmanager-fi");b.init();h=function(){f.addPushListener(function(b,a){b&&(a=a||[],"function"==typeof d[b]&&d[b].apply(d,a))});try{c(355),f.process(),d.init()}catch(e){b.reportError(e)}return d}();g.exports=h},584:function(g){g.exports={Mode:{PROD:"PROD",STAGE:"STAGE",PRELIVE:"PRELIVE",LOCAL:"LOCAL",DEMO:"DEMO"},Market:{CA:"CA",
DE:"DE",ES:"ES",FR:"FR",IT:"IT",MX:"MX",PL:"PL",UK:"UK",GB:"UK",US:"US",NL:"NL"},Language:{en_CA:"en_CA",de_DE:"de_DE",es_ES:"es_ES",fr_FR:"fr_FR",it_IT:"it_IT",es_MX:"es_MX",pl_PL:"pl_PL",en_GB:"en_GB",en_US:"en_US",nl_NL:"nl_NL",sv_SE:"sv_SE"},Tenant:{IONOS:"IONOS_DE",IONOS_DE:"IONOS_DE",IONOS_ES:"IONOS_ES",IONOS_FR:"IONOS_FR",IONOS_IT:"IONOS_IT",IONOS_MX:"IONOS_MX",IONOS_US:"IONOS_US",IONOS_UK:"IONOS_UK",IONOS_GB:"IONOS_UK",IONOS_CA:"IONOS_CA",IONOS_PL:"IONOS_PL",IONOS_CLOUD_DE:"IONOS_CLOUD_DE",
IONOS_CLOUD_ES:"IONOS_CLOUD_ES",IONOS_CLOUD_FR:"IONOS_CLOUD_FR",IONOS_CLOUD_IT:"IONOS_CLOUD_IT",IONOS_CLOUD_MX:"IONOS_CLOUD_MX",IONOS_CLOUD_US:"IONOS_CLOUD_US",IONOS_CLOUD_UK:"IONOS_CLOUD_UK",IONOS_CLOUD_GB:"IONOS_CLOUD_UK",IONOS_CLOUD_CA:"IONOS_CLOUD_CA",STRATO_DE:"STRATO_DE",STRATO_NL:"STRATO_NL",STRATO_ES:"STRATO_ES",STRATO_EA:"STRATO_EA",STRATO_FR:"STRATO_FR",STRATO_IT:"STRATO_IT",STRATO_GB:"STRATO_GB",STRATO_SE:"STRATO_SE",SEDO_DE:"SEDO_DE",SEDO_ES:"SEDO_ES",SEDO_UK:"SEDO_UK",SEDO_FR:"SEDO_FR",
SEDO_US:"SEDO_US",ARSYS:"ARSYS",ARSYS_FR:"ARSYS_FR",ARSYS_ES_EN:"ARSYS_ES_EN",FASTHOSTS:"FASTHOSTS",HOME_PL:"HOME_PL",HOME_PL_LEGACY:"HOME_PL_LEGACY",AZ_PL:"AZ_PL",HOMECLOUD_PL:"HOMECLOUD_PL",PIENSA_SOLUTIONS:"PIENSA_SOLUTIONS",UNITED_DOMAINS:"UNITED_DOMAINS",WORLD4YOU_DE:"WORLD4YOU_DE",WORLD4YOU_US:"WORLD4YOU_US",INTERNETX_DE:"INTERNETX_DE",INTERNETX_US:"INTERNETX_US"},DefaultLanguageForMarket:{CA:"en_CA",DE:"de_DE",ES:"es_ES",FR:"fr_FR",IT:"it_IT",MX:"es_MX",PL:"pl_PL",UK:"en_GB",US:"en_US",NL:"nl_NL"}}},
242:function(g,h,c){function f(){return a&&a.performance&&"function"==typeof a.performance.now?a.performance.now():(new Date).getTime()}var d,b,e=c(929),a=c(885),n=(a.document,"UNKNOWN"),k=n,l=n,m=!1,v=!1,t=!1,q=!1,r=!1,y=!1,z=f();g.exports={setClient:function(a){k=a||n},setClientVersion:function(a){l=a||n},setSentryDsn:function(a){m=a||!1},setSentryProject:function(a){v=a||!1},setSentryEnvironment:function(a){t=a||!1;y&&this.init()},init:function(){if(!1!==m)if(a.Sentry&&a.Sentry.BrowserClient&&
window.Sentry.Hub){var c={dsn:m,environment:t||"prod",beforeSend:function(a){return a.extra&&a.extra.oaoClient&&a.extra.oaoClient===k?a:null}};!1!==v&&(c.release=v+"@"+l);c=new a.Sentry.BrowserClient(c);(q=new a.Sentry.Hub).bindClient(c);y=!0;!1!==r&&(this.reportError(r,d,b),r=!1,d=!1,b=!1)}else c=e.getDefaultHostnameByScriptTag()||"frontend-services.ionos.com/t",e.loadScript("https://"+c+"/sentry/bundle.min.js",function(){this.init()}.bind(this))},reportError:function(a,c,e){if(!1===q)return this.init(),
r=a,d=c,void(b=e);q.withScope(function(b){b.setExtra("oaoClient",k);b.setExtra("oaoClientVersion",l);b.setExtra("oaoTimeSinceInit",function(a){if(!a)return!1;var b=f();return!!b&&Math.ceil(b-a)}(z));b.setExtra("oaoUrl",window.location.href||"");c&&b.setExtras(c);e&&b.setTags(e);q.captureException(a)})},getCurrentTime:f}},929:function(g,h,c){var f=c(242),d=c(885).document;g.exports={loadScript:function(b,c){var a,e,k,h=!1;return(e=d.createElement("script")).type="text/javascript",e.async=!0,"function"==
typeof c&&(k=function(){if(!(h||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState)){h=!0;try{c()}catch(u){f.reportError(u)}e.onload=null;e.onreadystatechange=null}},e.onload=k,e.onreadystatechange=k),e.src=b,(a=d.getElementsByTagName("script")[0]).parentNode.insertBefore(e,a),e},getDefaultHostnameByScriptTag:function(){var b;b=document;var c=[];b=b.querySelectorAll&&0<(c=b.querySelectorAll("#oaotag")).length?c[0]:null;if(!b)return!1;c=b.src;if(!c)return!1;c=c.replace("https://",
"");"//"===(c=c.replace("http://","")).substr(0,2)&&(c=c.substr(2));b=c.indexOf("/tag");return-1!==b&&c.substr(0,b)}}},318:function(g,h,c){var f=c(885).document;g.exports={build:function(c,b){var d,a,h=encodeURIComponent,f="",g="";if(!(c&&(f+=c.protocol?c.protocol+":":"",a=c.host)))return!1;if("/"===a.substr(-1)&&(a=a.substr(0,a.length-1)),f+=!0===b?a+"/":"//"+a+"/",c.path&&("/"===c.path.substr(0,1)&&(c.path=c.path.substr(1)),f+=c.path),c.query){for(d in c.query)c.query.hasOwnProperty(d)&&(g+=""===
g?"?":"\x26",g+=d+"\x3d"+h(c.query[d]));f+=g}return f},getQueryParams:function(c){var b,d,a,h,g={};if(!c&&(b=f.location,!b||!(c=b.search)))return g;if("?"===c.substr(0,1)&&(c=c.substr(1)),b=c.split("\x26"))for(c=0;c<b.length;c+=1)b[c]&&2===(d=b[c].split("\x3d")).length&&(a=d[0],h=d[1],a&&h&&(g[a]=h));return g},ensureSameProtocol:function(c){var b=f.location.protocol;return!!c&&(0===c.indexOf(b)||("http:"===b?c=c.replace("https://","http://"):"https:"===b&&(c=c.replace("http://","https://"))),c)},
isFullQualified:function(c){return!!c&&(0===c.indexOf("http://")||0===c.indexOf("https://"))}}},187:function(g){function h(){h.init.call(this)}function c(a){if("function"!=typeof a)throw new TypeError('The "listener" argument must be of type Function. Received type '+typeof a);}function f(a,b,d,e){var r,f,g;if(c(d),void 0===(f=a._events)?(f=a._events=Object.create(null),a._eventsCount=0):(void 0!==f.newListener&&(a.emit("newListener",b,d.listener?d.listener:d),f=a._events),g=f[b]),void 0===g)f[b]=
d,++a._eventsCount;else if("function"==typeof g?g=f[b]=e?[d,g]:[g,d]:e?g.unshift(d):g.push(d),0<(r=void 0===a._maxListeners?h.defaultMaxListeners:a._maxListeners)&&g.length>r&&!g.warned)g.warned=!0,d=Error("Possible EventEmitter memory leak detected. "+g.length+" "+String(b)+" listeners added. Use emitter.setMaxListeners() to increase limit"),d.name="MaxListenersExceededWarning",d.emitter=a,d.type=b,d.count=g.length,console&&console.warn&&console.warn(d);return a}function d(){if(!this.fired)return this.target.removeListener(this.type,
this.wrapFn),this.fired=!0,0===arguments.length?this.listener.call(this.target):this.listener.apply(this.target,arguments)}function b(a,b,c){a={fired:!1,wrapFn:void 0,target:a,type:b,listener:c};b=d.bind(a);return b.listener=c,a.wrapFn=b,b}function e(a,b,c){a=a._events;if(void 0===a)return[];b=a[b];if(void 0===b)c=[];else if("function"==typeof b)c=c?[b.listener||b]:[b];else if(c)for(c=Array(b.length),a=0;a<c.length;++a)c[a]=b[a].listener||b[a];else c=l(b,b.length);return c}function a(a){var b=this._events;
if(void 0!==b){a=b[a];if("function"==typeof a)return 1;if(void 0!==a)return a.length}return 0}function l(a,b){for(var c=Array(b),d=0;d<b;++d)c[d]=a[d];return c}function k(a,b,c,d){if("function"==typeof a.on)d.once?a.once(b,c):a.on(b,c);else{if("function"!=typeof a.addEventListener)throw new TypeError('The "emitter" argument must be of type EventEmitter. Received type '+typeof a);a.addEventListener(b,function A(e){d.once&&a.removeEventListener(b,A);c(e)})}}var m,u="object"==typeof Reflect?Reflect:
null,v=u&&"function"==typeof u.apply?u.apply:function(a,b,c){return Function.prototype.apply.call(a,b,c)};m=u&&"function"==typeof u.ownKeys?u.ownKeys:Object.getOwnPropertySymbols?function(a){return Object.getOwnPropertyNames(a).concat(Object.getOwnPropertySymbols(a))}:function(a){return Object.getOwnPropertyNames(a)};var t=Number.isNaN||function(a){return a!=a};g.exports=h;g.exports.once=function(a,b){return new Promise(function(c,d){function e(c){a.removeListener(b,f);d(c)}function f(){"function"==
typeof a.removeListener&&a.removeListener("error",e);c([].slice.call(arguments))}k(a,b,f,{once:!0});"error"!==b&&function(a,b,c){"function"==typeof a.on&&k(a,"error",b,c)}(a,e,{once:!0})})};h.EventEmitter=h;h.prototype._events=void 0;h.prototype._eventsCount=0;h.prototype._maxListeners=void 0;var q=10;Object.defineProperty(h,"defaultMaxListeners",{enumerable:!0,get:function(){return q},set:function(a){if("number"!=typeof a||0>a||t(a))throw new RangeError('The value of "defaultMaxListeners" is out of range. It must be a non-negative number. Received '+
a+".");q=a}});h.init=function(){void 0!==this._events&&this._events!==Object.getPrototypeOf(this)._events||(this._events=Object.create(null),this._eventsCount=0);this._maxListeners=this._maxListeners||void 0};h.prototype.setMaxListeners=function(a){if("number"!=typeof a||0>a||t(a))throw new RangeError('The value of "n" is out of range. It must be a non-negative number. Received '+a+".");return this._maxListeners=a,this};h.prototype.getMaxListeners=function(){return void 0===this._maxListeners?h.defaultMaxListeners:
this._maxListeners};h.prototype.emit=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(arguments[c]);var c="error"===a,d=this._events;if(void 0!==d)c=c&&void 0===d.error;else if(!c)return!1;if(c){var e;if(0<b.length&&(e=b[0]),e instanceof Error)throw e;b=Error("Unhandled error."+(e?" ("+e.message+")":""));throw b.context=e,b;}c=d[a];if(void 0===c)return!1;if("function"==typeof c)v(c,this,b);else for(e=c.length,d=l(c,e),c=0;c<e;++c)v(d[c],this,b);return!0};h.prototype.addListener=function(a,
b){return f(this,a,b,!1)};h.prototype.on=h.prototype.addListener;h.prototype.prependListener=function(a,b){return f(this,a,b,!0)};h.prototype.once=function(a,d){return c(d),this.on(a,b(this,a,d)),this};h.prototype.prependOnceListener=function(a,d){return c(d),this.prependListener(a,b(this,a,d)),this};h.prototype.removeListener=function(a,b){var d,e,f,g,h;if((c(b),void 0===(e=this._events))||void 0===(d=e[a]))return this;if(d===b||d.listener===b)0==--this._eventsCount?this._events=Object.create(null):
(delete e[a],e.removeListener&&this.emit("removeListener",a,d.listener||b));else if("function"!=typeof d){f=-1;for(g=d.length-1;0<=g;g--)if(d[g]===b||d[g].listener===b){h=d[g].listener;f=g;break}if(0>f)return this;if(0===f)d.shift();else{for(;f+1<d.length;f++)d[f]=d[f+1];d.pop()}1===d.length&&(e[a]=d[0]);void 0!==e.removeListener&&this.emit("removeListener",a,h||b)}return this};h.prototype.off=h.prototype.removeListener;h.prototype.removeAllListeners=function(a){var b,c;if(void 0===(c=this._events))return this;
if(void 0===c.removeListener)return 0===arguments.length?(this._events=Object.create(null),this._eventsCount=0):void 0!==c[a]&&(0==--this._eventsCount?this._events=Object.create(null):delete c[a]),this;if(0===arguments.length){var d=Object.keys(c);for(c=0;c<d.length;++c)"removeListener"!==(b=d[c])&&this.removeAllListeners(b);return this.removeAllListeners("removeListener"),this._events=Object.create(null),this._eventsCount=0,this}if("function"==typeof(b=c[a]))this.removeListener(a,b);else if(void 0!==
b)for(c=b.length-1;0<=c;c--)this.removeListener(a,b[c]);return this};h.prototype.listeners=function(a){return e(this,a,!0)};h.prototype.rawListeners=function(a){return e(this,a,!1)};h.listenerCount=function(b,c){return"function"==typeof b.listenerCount?b.listenerCount(c):a.call(b,c)};h.prototype.listenerCount=a;h.prototype.eventNames=function(){return 0<this._eventsCount?m(this._events):[]}},418:function(g){var h=Object.getOwnPropertySymbols,c=Object.prototype.hasOwnProperty,f=Object.prototype.propertyIsEnumerable;
g.exports=function(){try{if(!Object.assign)return!1;var c=new String("abc");if(c[5]="de","5"===Object.getOwnPropertyNames(c)[0])return!1;for(var b={},c=0;10>c;c++)b["_"+String.fromCharCode(c)]=c;if("0123456789"!==Object.getOwnPropertyNames(b).map(function(a){return b[a]}).join(""))return!1;var e={};return"abcdefghijklmnopqrst".split("").forEach(function(a){e[a]=a}),"abcdefghijklmnopqrst"===Object.keys(Object.assign({},e)).join("")}catch(a){return!1}}()?Object.assign:function(d,b){var e,a,g;if(null==
d)throw new TypeError("Object.assign cannot be called with null or undefined");g=Object(d);for(var k=1;k<arguments.length;k++){for(var l in e=Object(arguments[k]))c.call(e,l)&&(g[l]=e[l]);if(h){a=h(e);for(var m=0;m<a.length;m++)f.call(e,a[m])&&(g[a[m]]=e[a[m]])}}return g}},767:function(g,h,c){function f(b){b=d(b);return c(b)}function d(d){if(!c.o(b,d))throw d=Error("Cannot find module '"+d+"'"),d.code="MODULE_NOT_FOUND",d;return b[d]}var b={"./adserver":39,"./adserver.js":39,"./globalnavigation":609,
"./globalnavigation-prelive":11,"./globalnavigation-prelive.js":11,"./globalnavigation.js":609,"./inpagelayer":362,"./inpagelayer-prelive":177,"./inpagelayer-prelive.js":177,"./inpagelayer.js":362,"./password-indicator":319,"./password-indicator.js":319,"./privacy-consent":731,"./privacy-consent-prelive":8,"./privacy-consent-prelive.js":8,"./privacy-consent.js":731,"./pushnotifications":229,"./pushnotifications.js":229,"./statuspage":119,"./statuspage.js":119,"./surveys":150,"./surveys.js":150,"./tracking":456,
"./tracking.js":456,"./welcometour":488,"./welcometour.js":488};f.keys=function(){return Object.keys(b)};f.resolve=d;g.exports=f;f.id=767},885:function(g){g.exports=window}},w={};l.o=function(g,h){return Object.prototype.hasOwnProperty.call(g,h)};var x=l(925);(OAO=void 0===OAO?{}:OAO).c=x})();